package com.javabykiran.model;
// Generated 29 Apr, 2020 5:19:14 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Operatorlist generated by hbm2java
 */
@Entity
@Table(name = "operatorlist", catalog = "adminlte")
public class Operatorlist implements java.io.Serializable {

	private Integer id;
	private String operator;
	private String date;
	private String status;
	private String reason;

	public Operatorlist() {
	}

	public Operatorlist(String operator, String date, String status, String reason) {
		this.operator = operator;
		this.date = date;
		this.status = status;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "operator", nullable = false, length = 45)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "date", nullable = false, length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reason", nullable = false, length = 45)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
