package com.javabykiran.model;
// Generated 29 Apr, 2020 5:19:14 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statemaster generated by hbm2java
 */
@Entity
@Table(name = "statemaster", catalog = "adminlte")
public class Statemaster implements java.io.Serializable {

	private Integer sid;
	private String sname;

	public Statemaster() {
	}

	public Statemaster(String sname) {
		this.sname = sname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sid", unique = true, nullable = false)
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "sname", nullable = false, length = 45)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
